name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "New Features"
    semver-increment: minor
    when:
      labels: ["feature", "enhancement"]
  - title: "Bug Fixes"
    when:
      labels: ["fix", "bugfix", "bug"]
  - title: "Documentation"
    when:
      labels: ["documentation", "docs"]
  - title: "Maintenance"
    when:
      labels: ["chore", "maintenance", "ci"]
  - type: "version-resolver"
    semver-increment: "major"
    when:
      labels: ["major"]
  - type: "version-resolver"
    semver-increment: "patch"

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&'

template: |
  ## Changes

  $CHANGES
